-- https://www.hackerrank.com/challenges/placements/problem?isFullScreen=true

SELECT
    STUDENTS.NAME
FROM STUDENTS
INNER JOIN FRIENDS
    ON STUDENTS.ID = FRIENDS.ID
INNER JOIN PACKAGES
    ON STUDENTS.ID = PACKAGES.ID
WHERE (PACKAGES.SALARY -
     (SELECT PACKAGES.SALARY
     FROM PACKAGES
     WHERE ID = FRIENDS.FRIEND_ID)) < 0
ORDER BY
     (SELECT PACKAGES.SALARY
     FROM PACKAGES
     WHERE ID = FRIENDS.FRIEND_ID) ASC;

-- second solution without joins and unnecessary subqueries

SELECT S.NAME
FROM STUDENTS S, FRIENDS F, PACKAGES P1, PACKAGES P2
WHERE S.ID = F.ID
    AND S.ID = P1.ID
    AND F.FRIEND_ID = P2.ID
    AND P2.SALARY > P1.SALARY
ORDER BY P2.SALARY;